# Generated by Django 5.2.7 on 2025-10-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
