# Generated by Django 5.2.7 on 2025-11-04 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_appointment'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('profile_update', 'Mise à jour du profil'), ('password_change', 'Changement de mot de passe'), ('listing_view', "Consultation d'annonce"), ('listing_create', "Création d'annonce"), ('listing_update', "Modification d'annonce"), ('listing_delete', "Suppression d'annonce"), ('listing_publish', "Publication d'annonce"), ('favorite_add', 'Ajout aux favoris'), ('favorite_remove', 'Retrait des favoris'), ('search_save', 'Sauvegarde de recherche'), ('search_update', 'Modification de recherche'), ('search_delete', 'Suppression de recherche'), ('appointment_request', 'Demande de rendez-vous'), ('appointment_confirm', 'Confirmation de rendez-vous'), ('appointment_cancel', 'Annulation de rendez-vous'), ('appointment_complete', 'Rendez-vous terminé'), ('agent_add', "Ajout d'agent"), ('agent_update', "Modification d'agent"), ('agent_remove', "Suppression d'agent"), ('agency_approve', "Approbation d'agence"), ('agency_reject', "Rejet d'agence"), ('agency_update', "Modification d'agence"), ('user_create', "Création d'utilisateur"), ('user_update', "Modification d'utilisateur"), ('user_delete', "Suppression d'utilisateur")], max_length=50, verbose_name="Type d'activité")),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Métadonnées')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_activities', to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_us_user_id_506163_idx'), models.Index(fields=['activity_type'], name='accounts_us_activit_8a5b92_idx'), models.Index(fields=['created_at'], name='accounts_us_created_4de55c_idx')],
            },
        ),
    ]
